[project]
name = "google-sales-analytics-agent"
version = "0.1.0"
description = ""
authors = [
    {name = "jcarlossc",email = "jcarlossc1977@gmail.coom"}
]
readme = "README.md"
requires-python = ">=3.11,<4"
dependencies = [
    "pyyaml (>=6.0.3,<7.0.0)",
    "sqlalchemy (>=2.0.50,<3.0.0)",
    "pymysql (>=1.2.0,<2.0.0)",
    "pandas (>=3.0.3,<4.0.0)",
    "google-generativeai (>=0.8.6,<0.9.0)",
    "matplotlib (>=3.10.9,<4.0.0)",
    "reportlab (>=4.5.1,<5.0.0)",
    "google-genai (>=2.8.0,<3.0.0)"
]

[tool.poetry.scripts]
vendas = "google_sales_analytics_agent.main:main"

[tool.poetry]
packages = [{include = "google_sales_analytics_agent", from = "src"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "pytest (>=9.1.1,<10.0.0)"
]
